### ISSUE TITLE
Invisibilia

### ISSUE THREAD

**Issue by brownbat** [jetheis/MissingNPRPodcasts#4]
Does Invisibilia face the same issue? I'm not able to subscribe using gPodder using only http://www.npr.org/programs/invisibilia/archive

If so, would it be possible to support that one?

It's strange that some of their podcasts are broken in this way and some aren't. Maybe it isn't a business decision, maybe it's just a lack of awareness about alternative podcast managers and technologies and inconsistent coding on their end. If they're going out of their way to support iTunes... I think they just don't realize it's a broken experience for some people.

Thanks for the site, very impressive.

**Comment by jetheis** [comment]
Hi Thomas,

Does this podcast link work for your current setup?

http://www.npr.org/rss/podcast/podcast_detail.php?siteId=370162154

**Comment by brownbat** [comment]
It works perfectly.

Did I just fail at google? :)

Thank you, sorry about that!
